INSERT INTO `regions` (`id`, `name`, `link`) VALUES
(1, 'Республика Адыгея', 'https://vk.me/join/AJQ1d3MN8xngxoKQZfxQ3fuM'),
(2, 'Республика Алтай', 'https://vk.me/join/AJQ1d5VIvhkCQYvfu2JWPKER'),
(3, 'Алтайский край', 'https://vk.me/join/AJQ1d29Wxxmaw96ztyNsXozN'),
(4, 'Амурская область', 'https://vk.me/join/AJQ1d01cyRlfrj/5AVHFp/45'),
(5, 'Архангельская область', 'https://vk.me/join/AJQ1d1VftBmP7tA6y3GeWc7N' ),
(6, 'Астраханская область', 'https://vk.me/join/AJQ1d5Gs5hkoe/fyvMbvOu6C' ),
(7, 'Республика Башкортостан', 'https://vk.me/join/AJQ1d2qNxxmJtCLKAnfUpPKn'),
(8, 'Белгородская область', 'https://vk.me/join/AJQ1d3VF1Bm1CDl4E3XIPWk9' ),
(9, 'Брянская область', 'https://vk.me/join/AJQ1d0rs0hmq8k_br39HLDTB'),
(10, 'Республика Бурятия', 'https://vk.me/join/AJQ1d5zA_Rmcs8a7zi6uc/nO' ),
(11, 'Владимирская область', 'https://vk.me/join/AJQ1dyNXzhlrwy6Il5VhhhYp' ),
(12, 'Волгоградская область', 'https://vk.me/join/AJQ1d1/bxRnnE8sNqbl04Yoh' ),
(13, 'Вологодская областьб', 'https://vk.me/join/AJQ1d0vFxhlWNNDgYTulanuo'),
(14, 'Воронежская область', 'https://vk.me/join/AJQ1d/Th1Bls6KQBh5v8RXya'),
(15, 'Республика Дагестан', 'https://vk.me/join/AJQ1dwqF3hleIYrO3ZiRZX8W'),
(16, 'Еврейская АО', 'https://vk.me/join/AJQ1d80ZzBndYwpuFtuomC5N'),
(17, 'Забайкальский край', 'https://vk.me/join/AJQ1d7E/xhm7jlxpoOprV1yA '),
(18, 'Ивановская область', 'https://vk.me/join/AJQ1d8qd3hkrDgejFqeGKoy0 '),
(19, 'Республика Ингушетия', 'https://vk.me/join/AJQ1d/f1uxkmOutY24/InpUQ'),
(20, 'Иркутская область', 'https://vk.me/join/AJQ1d1gG7xnr13F0hjs_Ifdm '),
(21, 'Кабардино-Балкария', 'https://vk.me/join/AJQ1dwBbvBm80CIhEajoiUrF' ),
(22, 'Калининградская область', 'https://vk.me/join/AJQ1d3eSzxm_reHXlazlhTDU' ),
(23, 'Республика Калмыкия', 'https://vk.me/join/AJQ1d5oivRmUcEK0ycjBzY/6' ),
(24, 'Калужская область', 'https://vk.me/join/AJQ1d43g9Rm2Xb2gIauBn58u' ),
(25, 'Камчатский край', 'https://vk.me/join/AJQ1d5R6zRmsk2j5BgfaCHb9' ),
(26, 'Карачаево-Черкесия', 'https://vk.me/join/AJQ1dwIv4hnQwfyVEgPWTPlz' ),
(27, 'Республика Карелия', 'https://vk.me/join/AJQ1d762zhmyj8D/J_0s7sXC' ),
(28, 'Кемеровская область', 'https://vk.me/join/AJQ1d4BUxBnXef6PFNX2SLwd'),
(29, 'Кировская область', 'https://vk.me/join/AJQ1d_G91hk38blYl8QfCoXQ' ),
(30, 'Республика Коми', 'https://vk.me/join/AJQ1d/9kwBnqKxpLVDp0PQtl' ),
(31, 'Костромская область', 'https://vk.me/join/AJQ1d22MzRlaYug_95OAl3RT' ),
(32, 'Краснодарский край', 'https://vk.me/join/AJQ1d91F1xmbVDikV1xIEM0l' ),
(33, 'Красноярский край', 'https://vk.me/join/AJQ1d2PG8Bl3Aj1jC4Csac39' ),
(34, 'Республика Крым', 'https://vk.me/join/AJQ1d6/lzxlmOa/4RaZlHN2Z' ),
(35, 'Севастополь', 'https://vk.me/join/AJQ1d8as0RltYBLiGPdreESJ' ),
(36, 'Курганская область', 'https://vk.me/join/AJQ1d_rd2RmoJTFgM89CEwmO' ),
(37, 'Курская область', 'https://vk.me/join/AJQ1d_d_1BkNfRyZlLuJOBOO' ),
(38, 'Ленинградская область', 'https://vk.me/join/AJQ1d3583hmcDmHk19f42fIp' ),
(39, 'Липецкая область', 'https://vk.me/join/AJQ1dx3d5hnzIGCy1_xHS4wE' ),
(40, 'Магаданская область', 'https://vk.me/join/AJQ1d56LshkkxegD8VXIo32c' ),
(41, 'Республика Марий Эл', 'https://vk.me/join/AJQ1dzGg3Rm/laaGI32dq9zJ' ),
(42, 'Республика Мордовия', 'https://vk.me/join/AJQ1dwMZ0Rnud_gOlCGYRrk_' ),
(43, 'Москва', 'https://vk.me/join/AJQ1d/fTyRmbvWGXZTW0pP13' ),
(44, 'Московская область', 'https://vk.me/join/AJQ1dwEG5RlQVuAKUYmNFnRq' ),
(45, 'Мурманская область', 'https://vk.me/join/AJQ1d/e_/hlnEfO6hiHAkvyq' ),
(46, 'Ненецкий АО', 'https://vk.me/join/AJQ1d2/X2Rn2_CVA63AGEhBL' ),
(47, 'Нижегородская область', 'https://vk.me/join/AJQ1d4F5xBlYR4a7ZFNiz0tg' ),
(48, 'Новгородская область', 'https://vk.me/join/AJQ1d8HhqhlfR1zcsDd5OVSh '),
(49, 'Новосибирская область', 'https://vk.me/join/AJQ1d_xA1hnJ2EynLe8deBnz' ),
(50, 'Омская область', 'https://vk.me/join/AJQ1d/tyzhleAAyrpR3fCpaT' ),
(51, 'Оренбургская область', 'https://vk.me/join/AJQ1d__n4BkgsPiZwQ7Nz3l6' ),
(52, 'Орловская область', 'https://vk.me/join/AJQ1dzUNyhmWYUiT4NJBLjfk' ),
(53, 'Пензенская область', 'https://vk.me/join/AJQ1dwDJxhnQ9FPqHgW1aZW7' ),
(54, 'Пермский край', 'https://vk.me/join/AJQ1d7DduhmGyyReg6lgPZnF' ),
(55, 'Приморский край', 'https://vk.me/join/AJQ1d_Oi5hn7fycGHWVOMShU'),
(56, 'Псковская область', 'https://vk.me/join/AJQ1d5iy4BnFU2a_Rnrs_HHi' ),
(57, 'Ростовская область', 'https://vk.me/join/AJQ1d2mn0xl2zVj30wkBoLJw' ),
(58, 'Рязанская область', 'https://vk.me/join/AJQ1d046zhmVMp1IwIFK8opR' ),
(59, 'Самарская область', 'https://vk.me/join/AJQ1d9Cc3RnQ2Q0R2ji83XnS' ),
(60, 'Санкт-Петербург', 'https://vk.me/join/AJQ1d6ghqhlCXpcU1ERFDQsj' ),
(61, 'Саратовская область', 'https://vk.me/join/AJQ1d4xCnBmRboTecsR_GiC8' ),
(62, 'Сахалинская область', 'https://vk.me/join/AJQ1d/y93xmz7lsXfJdhkCwd '),
(63, 'Свердловская область', 'https://vk.me/join/AJQ1d4Oq4xl0cxyZox_xgFZL' ),
(64, 'Республика Северная Осетия - Алания', 'https://vk.me/join/AJQ1d5ix0hltOSNRGn1js_h4' ),
(65, 'Смоленская область', 'https://vk.me/join/AJQ1d9jlyBlBQBtlAF0z2Px0' ),
(66, 'Ставропольский край', 'https://vk.me/join/AJQ1d4iU6xlKkYVsS1nVh8hl' ),
(67, 'Тамбовская область', 'https://vk.me/join/AJQ1d8qq1hmJB7MSOW96wvhF '),
(68, 'Республика Татарстан', 'https://vk.me/join/AJQ1dw6q0xneE/Maby1Rp2CB '),
(69, 'Тверская область', 'https://vk.me/join/AJQ1dzM_3xlRK7NK8O6S30mI '),
(70, 'Томская область', 'https://vk.me/join/AJQ1d43xyRmUsuNBsMqI6S7/' ),
(71, 'Тульская область', 'https://vk.me/join/AJQ1dw_i0Rkh51vOY/Ft8BG4 '),
(72, 'Республика Тыва', 'https://vk.me/join/AJQ1d9is0xk1eeCuxBLn6JkG' ),
(73, 'Тюменская область', 'https://vk.me/join/AJQ1d5Yx7RlP4iH9uUIpakzE' ),
(74, 'Удмуртская Республика', 'https://vk.me/join/AJQ1d5az7hnnuNJPijkSwxNR' ),
(75, 'Ульяновская область', 'https://vk.me/join/AJQ1d6sIsBnUxfBf/t88JZWn' ),
(76, 'Хабаровский край', 'https://vk.me/join/AJQ1d2Mz5Blr8KKbXrpyfXpb' ),
(77, 'Республика Хакасия', 'https://vk.me/join/AJQ1d72zvxmxz1ydpQ1w9QBT '),
(78, 'Ханты-Мансийский АО', 'https://vk.me/join/AJQ1d8m/2Rlm6B5mPFt6Ud/7' ),
(79, 'Челябинская область', 'https://vk.me/join/AJQ1d4Sg9Bl_QOcDsy221gFQ '),
(80, 'Республика Чечня', 'https://vk.me/join/AJQ1d_18rBnRGXi8YhdbPy4C' ),
(81, 'Чувашская Республика', 'https://vk.me/join/AJQ1dzun2Bmg/u/pJhcebpH0' ),
(82, 'Чукотский АО', 'https://vk.me/join/AJQ1d0Me4hliZCAsJZJCuvkm' ),
(83, 'Республика Саха (Якутия)', 'https://vk.me/join/AJQ1d6Ij3xnj1PVSb1iZpjDS' ),
(84, 'Ямало-Ненецкий АО', 'https://vk.me/join/AJQ1d_1v5hltwgFgF6uufqTk '),
(85, 'Ярославская область', 'https://vk.me/join/AJQ1dxb33hmN3dUzpH76Orgl' );

